# The stanford_travisci_scripts repository contains external scripts
# used here to configure server and build a self-service site.
# https://github.com/SU-SWS/stanford_travisci_scripts
# This .travis.yml file assumes all scripts will be run from
# $TRAVIS_BUILD_DIR, ie. /home/travis/build/SU-SWS/$REPOSITORY_NAME

language: php
php:
  - '5.4'
  - '5.6'
  - '7.1'

sudo: required

cache:
  directories:
    - $HOME/.cache
    - $HOME/.composer/cache
    - $HOME/.drush/cache

mysql:
  database: drupal
  username: root
  encoding: utf8

before_install:
  # download external repository with Stanford Travis CI scripts
  - git clone https://github.com/SU-SWS/stanford_travisci_scripts.git $HOME/stanford_travisci_scripts
  - chmod +x $HOME/stanford_travisci_scripts/bin/*.sh
  # install composer packages
  - $HOME/stanford_travisci_scripts/bin/before_install.sh

install:
  # install self-service site, disable webauth module, start webserver and selenium webdriver
  - $HOME/stanford_travisci_scripts/bin/install.sh

before_script:
  # download linky_clicky, grab related tests, and start xvfb virtual display
  - $HOME/stanford_travisci_scripts/bin/before_script.sh

script:
  # make sure shell can find drush and run behat tests here, so Travis CI reports accurate results
  - $HOME/stanford_travisci_scripts/bin/script.sh
